export const ncrCalabarzonCities = [
  { city: 'Caloocan', province: 'Metro Manila', zip: '1400' },
  { city: 'Las Piñas', province: 'Metro Manila', zip: '1740' },
  { city: 'Makati', province: 'Metro Manila', zip: '1200' },
  { city: 'Malabon', province: 'Metro Manila', zip: '1470' },
  { city: 'Mandaluyong', province: 'Metro Manila', zip: '1550' },
  { city: 'Manila', province: 'Metro Manila', zip: '1000' },
  { city: 'Marikina', province: 'Metro Manila', zip: '1800' },
  { city: 'Muntinlupa', province: 'Metro Manila', zip: '1770' },
  { city: 'Navotas', province: 'Metro Manila', zip: '1485' },
  { city: 'Parañaque', province: 'Metro Manila', zip: '1700' },
  { city: 'Pasay', province: 'Metro Manila', zip: '1300' },
  { city: 'Pasig', province: 'Metro Manila', zip: '1600' },
  { city: 'Pateros', province: 'Metro Manila', zip: '1620' },
  { city: 'Quezon City', province: 'Metro Manila', zip: '1100' },
  { city: 'San Juan', province: 'Metro Manila', zip: '1500' },
  { city: 'Taguig', province: 'Metro Manila', zip: '1630' },
  { city: 'Valenzuela', province: 'Metro Manila', zip: '1440' },
  { city: 'Bacoor', province: 'Cavite', zip: '4102' },
  { city: 'Cavite City', province: 'Cavite', zip: '4100' },
  { city: 'Dasmariñas', province: 'Cavite', zip: '4114' },
  { city: 'Imus', province: 'Cavite', zip: '4103' },
  { city: 'Tagaytay', province: 'Cavite', zip: '4120' },
  { city: 'General Trias', province: 'Cavite', zip: '4107' },
  { city: 'Biñan', province: 'Laguna', zip: '4024' },
  { city: 'Cabuyao', province: 'Laguna', zip: '4025' },
  { city: 'Calamba', province: 'Laguna', zip: '4027' },
  { city: 'San Pablo', province: 'Laguna', zip: '4000' },
  { city: 'Santa Rosa', province: 'Laguna', zip: '4026' },
  { city: 'San Pedro', province: 'Laguna', zip: '4023' },
  { city: 'Batangas City', province: 'Batangas', zip: '4200' },
  { city: 'Lipa', province: 'Batangas', zip: '4217' },
  { city: 'Tanauan', province: 'Batangas', zip: '4232' },
  { city: 'Santo Tomas', province: 'Batangas', zip: '4234' },
  { city: 'Antipolo', province: 'Rizal', zip: '1870' },
  { city: 'Cainta', province: 'Rizal', zip: '1900' },
  { city: 'Taytay', province: 'Rizal', zip: '1920' },
  { city: 'Binangonan', province: 'Rizal', zip: '1940' },
  { city: 'Lucena', province: 'Quezon', zip: '4301' },
  { city: 'Tayabas', province: 'Quezon', zip: '4327' }
];

export const SPECIALIZATION_OPTIONS = [
  { value: 'Medicine', label: 'Medicine' },
  { value: 'Surgery', label: 'Surgery' },
  { value: 'Orthopedics', label: 'Orthopedics' },
  { value: 'Anesthesia', label: 'Anesthesia' },
  { value: 'Ophthalmology', label: 'Ophthalmology' },
  { value: 'Obstetrics-Gynecology', label: 'Obstetrics-Gynecology' },
  { value: 'Pediatrics', label: 'Pediatrics' },
  { value: 'Dermatology', label: 'Dermatology' },
  { value: 'Otolaryngology', label: 'Otolaryngology' },
  { value: 'Urology', label: 'Urology' },
  { value: 'Radiology', label: 'Radiology' },
  { value: 'Pathology', label: 'Pathology' },
  { value: 'Dental Medicine', label: 'Dental Medicine' }
];
